import { Link } from 'react-router-dom';

const journey = [['01','开户','账户申请 · 身份认证 · 风险评估'],['02','账户与资金','账户信息 · 入金出金 · 资金流水'],['03','发现产品','产品浏览 · 筛选 · 市场资讯'],['04','投资交易','产品选择 · 订单 · 交易状态'],['05','资产管理','总资产 · 持仓 · 投资组合'],['06','持续服务','交易记录 · 结单 · 通知']];
const capabilities = [['01','数字开户与账户','让客户在线开始投资旅程',['数字开户','身份与风险评估','账户状态','资料管理']],['02','财富产品与投资机会','将投资产品带到您的客户端',['产品浏览','产品详情','分类筛选','内容与资讯']],['03','一致的交易体验','从发现产品到完成投资',['交易下单','订单确认','交易状态','历史交易']],['04','资产与持仓','让客户随时掌握自己的资产',['总资产','资产配置','持仓组合','资金流水']],['05','持续客户服务','把一次交易延伸为持续关系',['电子结单','交易记录','消息通知','服务入口']]];

function Phone({brand,tone,screen}:{brand:string;tone:string;screen:'wealth'|'trade'|'invest'}) { return <div className={`wl-phone wl-phone-${tone}`} aria-label={`${brand} 白标投资终端示意`}><div className="wl-phone-screen"><header><b>{brand}</b><i /></header><small>总资产</small><strong>HKD 1,286,420</strong><div className="wl-chart">{[1,2,3,4,5,6].map(x=><i key={x}/>)}</div><div className="wl-phone-actions"><span>入金</span><span>交易</span><span>持仓</span></div><section><b>{screen==='trade'?'市场行情':screen==='invest'?'投资机会':'我的组合'}</b>{[1,2,3].map(x=><p key={x}><i/><span/><em/></p>)}</section></div></div> }
function Head({title,copy}:{title:string;copy?:string}) { return <div className="wl-head"><h2>{title}</h2>{copy&&<p>{copy}</p>}</div> }

export function WhiteLabelAppV1Page(){return <main className="wl-page" id="main">
  <section className="wl-hero" data-header-theme="inverse"><div className="wl-shell wl-hero-grid"><div className="wl-hero-copy"><h1>快速构建属于您的<br/>数字财富 App</h1><p>基于成熟财富科技基础设施，为金融机构快速构建自有品牌的财富或股票投资终端，连接客户、产品、交易与资产服务。</p><div className="wl-actions"><Link className="button button-accent" to="/contact">咨询白标方案 →</Link><a href="#infrastructure">了解平台能力 ↓</a></div><div className="wl-hero-line"><span>YOUR BRAND</span><i/><span>FINLOOP INFRASTRUCTURE</span></div></div><div className="wl-phone-stage"><Phone brand="NOVA" tone="blue" screen="wealth"/><Phone brand="ORBIT" tone="green" screen="trade"/><Phone brand="AURORA" tone="coral" screen="invest"/><div className="wl-stage-label">SAME INFRASTRUCTURE · YOUR BRAND</div></div></div></section>
  <section className="wl-section wl-value"><div className="wl-shell"><Head title="无需从零建设，也能拥有完整的数字投资终端" copy="从终端体验到财富核心，将原本分散的建设工作连接成可持续扩展的一套能力。"/><div className="wl-value-grid">{[['更快进入市场','减少从 App、财富系统到交易基础设施全部自行建设的复杂度。'],['自有品牌体验','以机构自己的品牌直接服务最终客户，而不是将用户导向第三方平台。'],['完整财富能力','在统一终端中连接账户、产品、交易、资产及持续客户服务。'],['持续扩展业务','财富核心与终端分离，后续可持续增加产品与服务。']].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
  <section className="wl-section wl-journey" id="journey"><div className="wl-shell"><Head title="覆盖投资者完整数字财富旅程" copy="从首次开户到持续服务，把每一次客户接触留在机构自己的品牌体验中。"/><div className="wl-journey-rail">{journey.map(([n,t,p])=><article key={n}><span>{n}</span><i/><h3>{t}</h3><p>{p}</p></article>)}</div><p className="wl-note">展示为白标终端建议能力模型，实际开放功能将根据机构业务与产品确认结果配置。</p></div></section>
  <section className="wl-section wl-capabilities"><div className="wl-shell"><Head title="围绕客户，而不是功能清单构建终端" copy="五类核心体验覆盖投资者从进入、投资到持续管理的主要任务。"/><div className="wl-cap-list">{capabilities.map(([n,t,h,points],i)=><article key={n as string}><div className="wl-cap-copy"><span>{n as string}</span><small>{t as string}</small><h3>{h as string}</h3><div>{(points as string[]).map(x=><b key={x}>{x}</b>)}</div></div><div className={`wl-cap-ui ui-${i}`}><header><i/><strong>{t as string}</strong><em/></header><section>{[1,2,3].map(x=><p key={x}><i/><span/><b/></p>)}</section><footer><span/><span/><span/></footer></div></article>)}</div><p className="wl-note">资产类别、股票行情与交易等具体功能范围需按实际方案确认。</p></div></section>
  <section className="wl-section wl-custom"><div className="wl-shell"><Head title="您的品牌，您的客户体验" copy="从视觉识别到业务流程，让数字终端与机构自身品牌和服务模式保持一致。"/><div className="wl-custom-board"><div className="wl-custom-nav">{[['BRAND','品牌表达'],['EXPERIENCE','体验结构'],['BUSINESS','业务配置']].map(([en,cn],i)=><article key={en}><span>0{i+1}</span><small>{en}</small><strong>{cn}</strong></article>)}</div><div className="wl-custom-center"><Phone brand="YOUR BRAND" tone="blue" screen="wealth"/></div><div className="wl-custom-options">{[['品牌表达','Logo · App 名称 · 品牌色 · 启动页'],['体验结构','首页 · 导航 · 产品入口 · 内容专区'],['业务配置','开户 · 产品类别 · 交易 · 客户服务']].map(([t,p])=><article key={t}><strong>{t}</strong><p>{p}</p></article>)}</div></div><p className="wl-note">品牌、UI、功能模块与业务流程的具体定制边界，以双方确认的实施方案为准。</p></div></section>
  <section className="wl-section wl-infrastructure" id="infrastructure"><div className="wl-shell"><Head title="不只是一个 App，背后是一套完整财富基础设施" copy="前端可以属于不同机构，背后的财富核心与交易连接能力可以统一复用。"/><div className="wl-stack">{[['YOUR CUSTOMER TERMINAL','White-label App / H5','开户 · 产品 · 交易 · 资产 · 服务'],['WEALTH CORE','FinOne','账户 · 客户 · 产品 · 交易 · 资产 · 运营'],['TRADING INFRASTRUCTURE','FinMix','交易 · 清结算 · 数据 · 上游连接'],['FINANCIAL NETWORK','全球金融网络','银行 · 券商 · 基金公司 · 产品机构']].map(([l,t,p],i)=><div key={l}><article className={i===1?'primary':''}><small>{l}</small><strong>{t}</strong><p>{p}</p></article>{i<3&&<i>↓</i>}</div>)}</div></div></section>
  <section className="wl-section wl-delivery"><div className="wl-shell"><Head title="选择适合业务的客户终端" copy="面向证券及经纪机构、财富管理机构、银行与数字平台，按实际合作模式规划客户入口。"/><div className="wl-delivery-grid">{[['原生 App','机构独立品牌移动应用。'],['H5 / 网页端','提供移动 Web 财富体验。'],['现有 App 集成','将财富能力接入机构已有数字平台。']].map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div><p className="wl-note">原生 App、H5 及现有应用集成的具体支持方式需按项目确认。</p></div></section>
  <section className="wl-cta"><div className="wl-shell"><h2>用您的品牌，开启下一代数字财富服务</h2><p>基于星路成熟的财富核心、产品和交易基础设施，构建符合机构业务模式的数字投资终端。</p><div><Link className="button button-light" to="/contact">咨询白标方案 →</Link><Link to="/products/finone">了解 FinOne</Link></div></div></section>
</main>}
