import { Link } from 'react-router-dom';

const shifts = [['MORE MODELS', '模型选择不断增加'], ['MORE APPLICATIONS', 'AI 从实验进入真实业务'], ['MORE GOVERNANCE', '成本、权限与稳定性成为企业问题']];
const fragments = [['01', '供应商分散', '多个模型供应商需要分别注册和接入。'], ['02', '接口分散', '协议、接口与开发方式各不相同。'], ['03', '成本分散', '价格、币种和账单难以统一查看。'], ['04', '治理分散', 'API Key、权限与日志散落在团队中。']];
const capabilities = [['DISCOVER', '模型发现'], ['CONNECT', '统一接入'], ['ROUTE', '智能调度'], ['GOVERN', '企业治理']];

function Head({ label, title, copy }: { label: string; title: string; copy?: string }) {
  return <div className="xzt-head"><small>{label}</small><h2>{title}</h2>{copy && <p>{copy}</p>}</div>;
}

function ProductUI({ title, variant = 'table' }: { title: string; variant?: 'table' | 'code' | 'chart' | 'keys' }) {
  return <div className={`xzt-ui xzt-ui-${variant}`} role="img" aria-label={`${title}产品界面占位`}>
    <aside><b>X</b>{[1,2,3,4,5].map(i => <i key={i}/>)}</aside>
    <div className="xzt-ui-main"><header><strong>{title}</strong><span/><span/></header><div className="xzt-ui-tools"><i/><i/><i/></div>
      {variant === 'chart' ? <div className="xzt-chart"><i/><i/><i/><i/><i/><b/></div> : variant === 'keys' ? <div className="xzt-key-tree">{['Organization','Project','Virtual Key','Model'].map((x,i)=><div key={x}><span>{x}</span><i style={{width:`${82-i*12}%`}}/></div>)}</div> : variant === 'code' ? <pre>{['POST /v1/chat/completions','model: selected_model','messages: [...]','stream: true'].map((x,i)=><code key={x}>{i+1}&nbsp;&nbsp;{x}</code>)}</pre> : <div className="xzt-ui-table">{[1,2,3,4,5].map(i=><div key={i}><b/><span/><span/><em/></div>)}</div>}
    </div>
  </div>;
}

export function XingZhiTongPage() {
  return <main className="xzt-page" id="main">
    <section className="xzt-hero" data-header-theme="inverse"><div className="xzt-shell xzt-hero-grid"><div className="xzt-hero-copy"><p className="xzt-kicker">星智通 <span>AI INFRASTRUCTURE</span></p><h1>一个入口，连接企业所需的 AI 模型</h1><p>通过统一 API 连接国内外主流 AI 模型，并集中管理模型路由、使用量、成本和访问权限，让企业更简单地构建和扩展 AI 应用。</p><div className="xzt-actions"><Link className="button button-accent" to="/contact">开始接入 →</Link><a href="#marketplace">探索模型 ↓</a></div></div><div className="xzt-routing" aria-label="统一入口连接多模型服务示意"><div className="xzt-request">APPLICATION <i/></div><strong><small>ONE API</small>星智通</strong><div className="xzt-models">{['TEXT','REASONING','IMAGE','VIDEO'].map(x=><span key={x}>{x}</span>)}</div></div></div></section>
    <nav className="xzt-nav" aria-label="星智通页面导航"><div className="xzt-shell"><a href="#platform">Platform</a><a href="#marketplace">模型广场</a><a href="#api">统一 API</a><a href="#routing">智能路由</a><a href="#governance">企业治理</a><a href="#workflow">如何运作</a></div></nav>

    <section className="xzt-section xzt-shift"><div className="xzt-shell"><Head label="THE MULTI-MODEL SHIFT" title="企业已经不再只使用一个 AI 模型" copy="不同模型在文本、推理、多模态和特定业务场景中各有所长。企业 AI 正从绑定单一模型，进入按任务选择和组合模型的新阶段。"/><div className="xzt-shift-grid">{shifts.map(([a,b],i)=><article key={a}><span>0{i+1}</span><small>{a}</small><h3>{b}</h3></article>)}</div></div></section>
    <section className="xzt-section xzt-fragment"><div className="xzt-shell"><Head label="AI INFRASTRUCTURE FRAGMENTATION" title="每增加一个模型，不应该再增加一套接入和管理成本"/><div className="xzt-fragment-grid">{fragments.map(([n,t,p])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="xzt-section xzt-platform" id="platform"><div className="xzt-shell"><Head label="ONE AI ACCESS LAYER" title="把多模型复杂度留在平台，把统一接口留给应用" copy="星智通将模型接入、路由、计费和治理集中到一个 AI 服务层，使上层应用无需分别管理多个模型供应商。"/><div className="xzt-capabilities">{capabilities.map(([a,b],i)=><article key={a}><span>0{i+1}</span><small>{a}</small><strong>{b}</strong></article>)}</div><p className="xzt-statement">Connect once. Use multiple models.</p></div></section>
    <section className="xzt-section xzt-marketplace" id="marketplace"><div className="xzt-shell"><Head label="MODEL MARKETPLACE" title="在一个地方发现和比较不同 AI 模型"/><div className="xzt-feature"><ProductUI title="Model Marketplace"/><div className="xzt-feature-copy">{[['DISCOVER','按模型、供应商、端点和标签搜索。'],['COMPARE','比较模型能力、输入输出与价格。'],['DECIDE','根据具体任务更快完成模型选型。'],['CONNECT','从选择直接进入 API 使用。']].map(([a,b])=><article key={a}><small>{a}</small><p>{b}</p></article>)}</div></div></div></section>
    <section className="xzt-section xzt-api" id="api"><div className="xzt-shell"><Head label="UNIFIED API" title="一套接口，调用不同模型" copy="通过统一 API 和兼容协议，让开发团队减少针对不同模型重复编写和维护接入代码的成本。"/><div className="xzt-api-grid"><div className="xzt-api-list">{[['OPENAI-COMPATIBLE','兼容常见 OpenAI 接口形式'],['NATIVE PROTOCOLS','支持 Anthropic、Gemini 等相关协议'],['SDK & CLI','支持主流开发 SDK、CLI 及开发工具'],['ONE CONNECTION','减少模型切换与迁移成本']].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div><ProductUI title="API 接入" variant="code"/></div></div></section>
    <section className="xzt-section xzt-routing-section" id="routing"><div className="xzt-shell"><Head label="INTELLIGENT ROUTING" title="不让应用依赖单一模型线路"/><div className="xzt-route-map"><div>应用请求</div><strong>智能路由<small>ROUTING LAYER</small></strong><div>{['通道 A','通道 B','通道 C'].map(x=><span key={x}>{x}<i/></span>)}</div></div><div className="xzt-route-values">{[['RELIABLE ACCESS','提高模型服务连续性'],['FLEXIBLE ROUTING','根据线路状态和配置调度请求'],['AUTOMATIC FAILOVER','单一路径异常时切换其他可用线路'],['SCALE','支持更大规模的 AI 应用调用']].map(([a,b])=><article key={a}><small>{a}</small><p>{b}</p></article>)}</div></div></section>
    <section className="xzt-section xzt-cost"><div className="xzt-shell"><Head label="USAGE & COST CONTROL" title="让 AI 使用量和成本变得可见"/><div className="xzt-feature xzt-feature-reverse"><ProductUI title="Usage & Cost" variant="chart"/><div className="xzt-feature-copy">{[['KNOW','知道团队用了多少。'],['UNDERSTAND','知道成本花在哪些模型。'],['CONTROL','设置相应额度和预算。'],['OPTIMIZE','通过价格、缓存及路由策略优化使用成本。']].map(([a,b])=><article key={a}><small>{a}</small><p>{b}</p></article>)}</div></div></div></section>
    <section className="xzt-section xzt-governance" id="governance"><div className="xzt-shell"><Head label="ENTERPRISE GOVERNANCE" title="从个人 API Key，升级为企业 AI 治理" copy="将模型访问按组织、项目和虚拟密钥统一管理，让权限、凭证和使用记录保持清晰。"/><div className="xzt-govern-grid"><ProductUI title="Enterprise Governance" variant="keys"/><div className="xzt-govern-list">{[['CONTROL ACCESS','控制谁可以使用什么模型'],['SEPARATE PROJECTS','不同团队和项目分别管理'],['AUDIT USAGE','保留调用和使用记录'],['PROTECT CREDENTIALS','减少上游真实 API Key 的分散暴露']].map(([a,b],i)=><article key={a}><span>0{i+1}</span><small>{a}</small><h3>{b}</h3></article>)}</div></div></div></section>
    <section className="xzt-section xzt-workflow" id="workflow"><div className="xzt-shell"><Head label="CONFIGURE → CONNECT → MONITOR" title="从模型接入到运行监控，一个平台完成"/><div className="xzt-workflow-grid">{[['01','CONFIGURE','配置','添加模型渠道与密钥，设置项目和权限。'],['02','CONNECT','连接','通过统一或兼容 API 接入应用。'],['03','MONITOR','监控','持续查看使用量、成本、性能与服务状态。']].map(([n,a,t,p])=><article key={n}><span>{n}</span><small>{a}</small><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="xzt-section xzt-stack"><div className="xzt-shell"><Head label="AI INFRASTRUCTURE STACK" title="为上层 AI 应用提供统一模型服务"/><div className="xzt-stack-map">{[['AI APPLICATIONS','星路通 · FAI · 企业 AI 应用 · 智能客服'],['AGENTS & OPERATIONS','Agent 编排 · Workflow · Data / Knowledge'],['MAAS · 星智通','Model Marketplace · Unified API · Routing'],['MODEL PROVIDERS','文本 · 推理 · 图像 · 视频 · 多模态']].map(([a,b],i)=><article className={i===2?'primary':''} key={a}><small>{a}</small><strong>{b}</strong></article>)}</div></div></section>
    <section className="xzt-section xzt-usecases"><div className="xzt-shell"><Head label="BUILT FOR AI APPLICATIONS" title="为不同企业 AI 使用方式提供模型服务"/><div className="xzt-usecase-grid">{[['AI / 应用开发','统一接入不同模型。'],['智能客服','为客服与知识应用提供模型服务。'],['内容生成','根据任务调用不同模型。'],['数据与研究','按任务选择推理与内容模型。'],['多模态应用','连接文本、图像和视频等模型服务。']].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
    <section className="xzt-cta"><div className="xzt-shell"><h2>用一个 AI 入口，连接您的下一项智能应用</h2><p>无论您正在构建企业 AI 应用、Agent、智能客服还是开发工具，星智通都可以通过统一模型服务帮助团队更简单地连接和管理多模型能力。</p><div><Link className="button button-light" to="/contact">开始接入 →</Link><Link to="/contact">联系企业团队</Link></div></div></section>
  </main>;
}
